require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CcspublicationsController do

  # This should return the minimal set of attributes required to create a valid
  # Ccspublication. As you add validations to Ccspublication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "body" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CcspublicationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ccspublications as @ccspublications" do
      ccspublication = Ccspublication.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ccspublications).should eq([ccspublication])
    end
  end

  describe "GET show" do
    it "assigns the requested ccspublication as @ccspublication" do
      ccspublication = Ccspublication.create! valid_attributes
      get :show, {:id => ccspublication.to_param}, valid_session
      assigns(:ccspublication).should eq(ccspublication)
    end
  end

  describe "GET new" do
    it "assigns a new ccspublication as @ccspublication" do
      get :new, {}, valid_session
      assigns(:ccspublication).should be_a_new(Ccspublication)
    end
  end

  describe "GET edit" do
    it "assigns the requested ccspublication as @ccspublication" do
      ccspublication = Ccspublication.create! valid_attributes
      get :edit, {:id => ccspublication.to_param}, valid_session
      assigns(:ccspublication).should eq(ccspublication)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ccspublication" do
        expect {
          post :create, {:ccspublication => valid_attributes}, valid_session
        }.to change(Ccspublication, :count).by(1)
      end

      it "assigns a newly created ccspublication as @ccspublication" do
        post :create, {:ccspublication => valid_attributes}, valid_session
        assigns(:ccspublication).should be_a(Ccspublication)
        assigns(:ccspublication).should be_persisted
      end

      it "redirects to the created ccspublication" do
        post :create, {:ccspublication => valid_attributes}, valid_session
        response.should redirect_to(Ccspublication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ccspublication as @ccspublication" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ccspublication.any_instance.stub(:save).and_return(false)
        post :create, {:ccspublication => { "body" => "invalid value" }}, valid_session
        assigns(:ccspublication).should be_a_new(Ccspublication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ccspublication.any_instance.stub(:save).and_return(false)
        post :create, {:ccspublication => { "body" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ccspublication" do
        ccspublication = Ccspublication.create! valid_attributes
        # Assuming there are no other ccspublications in the database, this
        # specifies that the Ccspublication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ccspublication.any_instance.should_receive(:update).with({ "body" => "MyText" })
        put :update, {:id => ccspublication.to_param, :ccspublication => { "body" => "MyText" }}, valid_session
      end

      it "assigns the requested ccspublication as @ccspublication" do
        ccspublication = Ccspublication.create! valid_attributes
        put :update, {:id => ccspublication.to_param, :ccspublication => valid_attributes}, valid_session
        assigns(:ccspublication).should eq(ccspublication)
      end

      it "redirects to the ccspublication" do
        ccspublication = Ccspublication.create! valid_attributes
        put :update, {:id => ccspublication.to_param, :ccspublication => valid_attributes}, valid_session
        response.should redirect_to(ccspublication)
      end
    end

    describe "with invalid params" do
      it "assigns the ccspublication as @ccspublication" do
        ccspublication = Ccspublication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ccspublication.any_instance.stub(:save).and_return(false)
        put :update, {:id => ccspublication.to_param, :ccspublication => { "body" => "invalid value" }}, valid_session
        assigns(:ccspublication).should eq(ccspublication)
      end

      it "re-renders the 'edit' template" do
        ccspublication = Ccspublication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ccspublication.any_instance.stub(:save).and_return(false)
        put :update, {:id => ccspublication.to_param, :ccspublication => { "body" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ccspublication" do
      ccspublication = Ccspublication.create! valid_attributes
      expect {
        delete :destroy, {:id => ccspublication.to_param}, valid_session
      }.to change(Ccspublication, :count).by(-1)
    end

    it "redirects to the ccspublications list" do
      ccspublication = Ccspublication.create! valid_attributes
      delete :destroy, {:id => ccspublication.to_param}, valid_session
      response.should redirect_to(ccspublications_url)
    end
  end

end
